import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { UserContextProvider } from "@/context/user-context";
import userGet from "@/lib/actions/user-get";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: user } = await userGet();

  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <UserContextProvider user={user}>
          {user && <Header />}
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
