import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { usuarios } from "@/lib/data";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        {usuarios[1].logado || usuarios[0].logado ? <Header /> : null}
        
        <h1>Usuario Comum</h1>
          {usuarios[0].logado ? 'Logado' : 'Não logado'}
        <h1>Usuario adm</h1>
          {usuarios[1].logado ? 'Logado' : 'Não logado'}
        {children}
      
        </body>
    </html>
  );
}
